# Shell variables
# Generated by 'wal'
wallpaper='/home/pree/Media/wallpapers/favs/wallhaven-gp8zoe.jpg'

# Special
background='#191919'
foreground='#cfe3d8'
cursor='#cfe3d8'

# Colors
color0='#191919'
color1='#6C9258'
color2='#7EC150'
color3='#97A956'
color4='#A9B351'
color5='#3C6B92'
color6='#629CB0'
color7='#cfe3d8'
color8='#909e97'
color9='#6C9258'
color10='#7EC150'
color11='#97A956'
color12='#A9B351'
color13='#3C6B92'
color14='#629CB0'
color15='#cfe3d8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
