# Shell variables
# Generated by 'wal'
wallpaper='/home/pree/wallpapers/favs/12.jpg'

# Special
background='#191919'
foreground='#ece9e1'
cursor='#ece9e1'

# Colors
color0='#191919'
color1='#827E8A'
color2='#A29D9E'
color3='#CDC4B6'
color4='#D8D6CD'
color5='#DEDFD8'
color6='#E9DDCA'
color7='#ece9e1'
color8='#a5a39d'
color9='#827E8A'
color10='#A29D9E'
color11='#CDC4B6'
color12='#D8D6CD'
color13='#DEDFD8'
color14='#E9DDCA'
color15='#ece9e1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
