# Shell variables
# Generated by 'wal'
wallpaper='/home/pree/wallpapers/favs/72.jpg'

# Special
background='#191919'
foreground='#edece5'
cursor='#edece5'

# Colors
color0='#191919'
color1='#71B8CF'
color2='#98A8A0'
color3='#B8C2BB'
color4='#B6CACB'
color5='#CCD7D4'
color6='#D8E5DF'
color7='#edece5'
color8='#a5a5a0'
color9='#71B8CF'
color10='#98A8A0'
color11='#B8C2BB'
color12='#B6CACB'
color13='#CCD7D4'
color14='#D8E5DF'
color15='#edece5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
