require('basic')
require('keybinds')
require('autocommands')
require('filetypes')
require('lazy-bootstrap')
require("plugins")

require('plugins.colorizer')
require('plugins.treesitter')
require('plugins.oil')
require('plugins.nvim-sorround')
require('plugins.lspconfig')
require('plugins.colorscheme')
require('plugins.statusline')
require('plugins.fzf')
--require('plugins.mkdp')
--require('nvim-web-devicons')
