require('basic')
require('keybinds')
require('autocommands')
require('filetypes')
require('lazy-bootstrap')
require("plugins")

require('plugins.colorscheme.everforest')
require('plugins.colorscheme.override')
require('plugins.kittyscrollback')
require('plugins.colorizer')
require('plugins.treesitter')
require('plugins.oil')
require('plugins.nvim-sorround')
require('plugins.lspconfig')
require('plugins.statusline')
require('plugins.fzf')
